### ISSUE TITLE
`qunit-initializer` included in production build

### ISSUE THREAD

**Issue by btecu** [null-null-null/ember-message-bus#3]
Is `qunit-initializer` required in production builds? Could it be not included?

**Comment by null-null-null** [comment]
This [line](https://github.com/null-null-null/ember-message-bus/blob/master/addon/instance-initializers/ember-message-bus/qunit-initializer.js#L22) should prevent it from executing most of the initialization, but I suspect you're asking if we could remove it at an even higher level, perhaps in the `treeForAddon` or something?

**Comment by btecu** [comment]
Yes, I was thinking it would be 1.5 KB less in the production build.

**Comment by null-null-null** [comment]
I'm still wrapping my head around how to use `index.js`, but that seems like a reasonable request. I'll look into it.

**Comment by null-null-null** [comment]
Fixed on `v0.2.1`. Not sure if it's the best approach, but would need to see examples of other repos doing it for inspiration.

**Comment by btecu** [comment]
Thanks!
