### ISSUE TITLE
usage example not clear

### ISSUE THREAD

**Issue by qknight** [null-null-null/ember-message-bus#4]
the usage example given https://github.com/null-null-null/ember-message-bus#usage does not work for me.

you say: "First, add the BusPublisherMixin to something..." and then in the next paragraph you add it somewhere else as well?!

what is the `addService` for?

**Comment by qknight** [comment]
i got it now working. the reason why it didn't work as expected was rather odd:

# app/router.js
```
Router.map(function() {
  this.route('services', function() {
    this.route('show', { path: '/:service_id' });
  });
});
```

# works for the controller but not for the subcontroller

* it works in `app/controllers/services/index.js` but 
* fails in `app/controllers/services/show.js`

**Comment by null-null-null** [comment]
Sorry for the late response, and thanks for reporting this. When you say it's not working, what seems to be broken? Are you getting any errors in the console? Or is it simply not behaving as expected?

**Comment by qknight** [comment]
i got it working at last! however, the example is really not clear. if i come up with a better example usage i try a PR.

thanks for your feedback.

**Comment by null-null-null** [comment]
Documentation updated to reflect changes to the api. Let me know if they're unclear!

**Comment by rhengeveld** [comment]
Thanks for this addon, this is _exactly_ what I need in my application.

The documentation is very clear, but you might want to mention `unsubscribe` / `unsubscribeAll` to cover it all. Also that _destroyed_ objects are automatically unsubscribed, so you don't have to worry about that. I was **very** pleased to find out the code got it covered 😄
